"""
Setup wizard API for Argus.
Writes to /app/host.env which is mounted from the host's .env file.
"""
import os
import re
import httpx
from pathlib import Path
from fastapi import APIRouter
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional

router = APIRouter()

# /app/host.env is the host's .env file mounted via docker-compose
# This is what Docker reads on startup — writing here persists across restarts
HOST_ENV_PATH = Path("/app/host.env")


def _is_setup_complete() -> bool:
    required = ["AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID"]
    return all(os.getenv(v, "").strip() for v in required)


@router.get("/status")
async def setup_status():
    complete = _is_setup_complete()
    return {
        "setup_complete": complete,
        "provider": os.getenv("AUTH_PROVIDER", "entra"),
        "missing": [
            v for v in ["AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID"]
            if not os.getenv(v, "").strip()
        ] if not complete else [],
    }


@router.get("/redirect-uri")
async def get_redirect_uri():
    frontend_url = os.getenv("FRONTEND_URL", "http://localhost:3000")
    backend_url  = frontend_url.replace(":3000", ":8000")
    return {
        "redirect_uri": f"{backend_url}/api/auth/callback",
        "frontend_url": frontend_url,
    }


class ValidatePayload(BaseModel):
    provider:      str = "entra"
    client_id:     str
    client_secret: str
    tenant_id:     str


@router.post("/validate")
async def validate_credentials(payload: ValidatePayload):
    errors = []
    uuid_re = re.compile(
        r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', re.I
    )
    if not uuid_re.match(payload.client_id.strip()):
        errors.append("Client ID doesn't look like a valid UUID")
    if not uuid_re.match(payload.tenant_id.strip()):
        errors.append("Tenant ID doesn't look like a valid UUID")
    if len(payload.client_secret.strip()) < 10:
        errors.append("Client secret looks too short — copy the Value, not the Secret ID")
    if errors:
        return JSONResponse({"valid": False, "errors": errors}, status_code=400)

    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            url = f"https://login.microsoftonline.com/{payload.tenant_id.strip()}/v2.0/.well-known/openid-configuration"
            r = await client.get(url)
            if r.status_code == 200:
                return {
                    "valid":   True,
                    "tenant":  payload.tenant_id,
                    "issuer":  r.json().get("issuer", ""),
                    "message": "Successfully connected to Microsoft identity platform",
                }
            else:
                return JSONResponse({
                    "valid": False,
                    "errors": ["Tenant ID not found — verify your Directory (tenant) ID"]
                }, status_code=400)
    except httpx.TimeoutException:
        return JSONResponse({
            "valid": False,
            "errors": ["Could not reach Microsoft — check network/firewall"]
        }, status_code=400)
    except Exception as e:
        return JSONResponse({"valid": False, "errors": [str(e)]}, status_code=400)


class CompletePayload(BaseModel):
    provider:      str = "entra"
    client_id:     str
    client_secret: str
    tenant_id:     str
    frontend_url:  str = "http://localhost:3000"
    admin_email:   Optional[str] = None
    rescan_hours:  int = 24


@router.post("/complete")
async def complete_setup(payload: CompletePayload):
    import secrets as _secrets

    jwt_secret   = _secrets.token_hex(32)
    backend_url  = payload.frontend_url.replace(":3000", ":8000")
    redirect_uri = f"{backend_url}/api/auth/callback"

    env_content = f"""# Argus Configuration — generated by setup wizard
DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/ai_scanner
AUTH_PROVIDER={payload.provider}
AZURE_CLIENT_ID={payload.client_id.strip()}
AZURE_CLIENT_SECRET={payload.client_secret.strip()}
AZURE_TENANT_ID={payload.tenant_id.strip()}
AUTH_REDIRECT_URI={redirect_uri}
FRONTEND_URL={payload.frontend_url}
JWT_SECRET={jwt_secret}
JWT_EXPIRE_HOURS=8
RESCAN_INTERVAL_HOURS={payload.rescan_hours}
RETENTION_SCANS_DAYS=90
RETENTION_TRIAGE_DAYS=30
"""
    if payload.admin_email:
        env_content += f"ALERT_RECIPIENTS={payload.admin_email}\n"

    try:
        HOST_ENV_PATH.write_text(env_content)
        return {
            "success":      True,
            "message":      "Configuration written to host .env file.",
            "redirect_uri": redirect_uri,
            "next_step":    "restart",
        }
    except Exception as e:
        return JSONResponse({
            "success": False,
            "error": f"Could not write to {HOST_ENV_PATH}: {str(e)}. Set env vars manually."
        }, status_code=500)