"""
PDF report generation for Argus AI Shadow IT Scanner.
Produces two report types:
  - Executive Summary  (2 pages, leadership-friendly)
  - Technical Report   (full inventory + detail)
"""
from io import BytesIO
from datetime import datetime
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame,
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics import renderPDF
from reportlab.pdfgen import canvas

# ── Colour palette ────────────────────────────────────────────────────────────
BG        = colors.HexColor("#070b12")
SURFACE   = colors.HexColor("#0c1220")
LINE      = colors.HexColor("#1e2d45")
TXT1      = colors.HexColor("#e2eaf6")
TXT2      = colors.HexColor("#7a92b4")
TXT3      = colors.HexColor("#3d5270")
CYAN      = colors.HexColor("#00c8e0")
RED       = colors.HexColor("#f04438")
ORANGE    = colors.HexColor("#f97316")
YELLOW    = colors.HexColor("#eab308")
GREEN     = colors.HexColor("#22c55e")
WHITE     = colors.white
BLACK     = colors.black

RISK_COLOR = {
    "CRITICAL": RED,
    "HIGH":     ORANGE,
    "MEDIUM":   YELLOW,
    "LOW":      GREEN,
}

W, H = A4  # 595 x 842 pts


# ── Helpers ───────────────────────────────────────────────────────────────────

def risk_color(level: str):
    return RISK_COLOR.get(level, TXT3)


def _header_footer(c: canvas.Canvas, doc, report_type: str, org: str):
    """Draw header bar and footer on every page."""
    c.saveState()

    # Header bar
    c.setFillColor(SURFACE)
    c.rect(0, H - 28*mm, W, 28*mm, fill=1, stroke=0)
    c.setFillColor(CYAN)
    c.rect(0, H - 28*mm, 3, 28*mm, fill=1, stroke=0)

    # Logo text
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(TXT1)
    c.drawString(14*mm, H - 14*mm, "ARGUS")
    c.setFont("Helvetica", 8)
    c.setFillColor(TXT3)
    c.drawString(14*mm, H - 20*mm, "AI SHADOW IT SCANNER")

    # Report type + org
    c.setFont("Helvetica", 8)
    c.setFillColor(TXT2)
    label = f"{report_type}  ·  {org}  ·  {datetime.utcnow().strftime('%d %b %Y')}"
    c.drawRightString(W - 14*mm, H - 14*mm, label)
    c.setFillColor(CYAN)
    c.drawRightString(W - 14*mm, H - 20*mm, f"Page {doc.page}")

    # Footer line
    c.setStrokeColor(LINE)
    c.setLineWidth(0.5)
    c.line(14*mm, 14*mm, W - 14*mm, 14*mm)
    c.setFont("Helvetica", 7)
    c.setFillColor(TXT3)
    c.drawString(14*mm, 9*mm, "CONFIDENTIAL — Generated by Argus AI Shadow IT Scanner")
    c.drawRightString(W - 14*mm, 9*mm, "argus.internal")

    c.restoreState()


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", fontName="Helvetica-Bold",   fontSize=22, textColor=TXT1,  spaceAfter=4,  leading=26),
        "h2": ParagraphStyle("h2", fontName="Helvetica-Bold",   fontSize=13, textColor=TXT1,  spaceAfter=3,  leading=18, spaceBefore=14),
        "h3": ParagraphStyle("h3", fontName="Helvetica-Bold",   fontSize=10, textColor=CYAN,  spaceAfter=2,  leading=14, spaceBefore=8),
        "body": ParagraphStyle("body", fontName="Helvetica",    fontSize=9,  textColor=TXT2,  spaceAfter=4,  leading=14),
        "mono": ParagraphStyle("mono", fontName="Courier",      fontSize=8,  textColor=TXT2,  spaceAfter=2,  leading=12),
        "label": ParagraphStyle("label", fontName="Helvetica-Bold", fontSize=8, textColor=TXT3, spaceAfter=0, leading=11),
        "note": ParagraphStyle("note", fontName="Helvetica-Oblique", fontSize=8, textColor=TXT3, spaceAfter=4, leading=12),
        "crumb": ParagraphStyle("crumb", fontName="Courier",    fontSize=8,  textColor=TXT3,  spaceAfter=2,  leading=11, charSpace=1),
    }


def _kpi_row(summary: dict) -> Table:
    """4-cell KPI strip."""
    cells = [
        ("CRITICAL", summary.get("critical", 0), RED),
        ("HIGH",     summary.get("high",     0), ORANGE),
        ("MEDIUM",   summary.get("medium",   0), YELLOW),
        ("LOW",      summary.get("low",      0), GREEN),
    ]
    data = [[
        _kpi_cell(label, count, color) for label, count, color in cells
    ]]
    t = Table(data, colWidths=[(W - 28*mm) / 4] * 4, rowHeights=[28*mm])
    t.setStyle(TableStyle([
        ("BOX",         (0,0), (-1,-1), 0.5, LINE),
        ("INNERGRID",   (0,0), (-1,-1), 0.5, LINE),
        ("BACKGROUND",  (0,0), (-1,-1), SURFACE),
        ("TOPPADDING",  (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0),(-1,-1), 8),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
    ]))
    return t


def _kpi_cell(label: str, value: int, color) -> Paragraph:
    return Paragraph(
        f'<font name="Courier" size="7" color="#{color.hexval()[2:].upper()}">{label}</font><br/>'
        f'<font name="Courier-Bold" size="26" color="#{color.hexval()[2:].upper()}">{value}</font>',
        ParagraphStyle("kpi", leading=32, spaceAfter=0)
    )


def _risk_bar(score: float, level: str, width_pts=80) -> Drawing:
    """Inline mini bar showing risk score 0-10."""
    d = Drawing(width_pts, 6)
    d.add(Rect(0, 0, width_pts, 6, fillColor=LINE, strokeColor=None))
    fill_w = (score / 10.0) * width_pts
    d.add(Rect(0, 0, fill_w, 6, fillColor=risk_color(level), strokeColor=None))
    return d


def _section_header(title: str, s: dict):
    return [
        HRFlowable(width="100%", thickness=0.5, color=LINE, spaceAfter=6),
        Paragraph(title.upper(), s["h3"]),
    ]


# ── Executive Summary ─────────────────────────────────────────────────────────

def build_executive_summary(
    org: str,
    summary: dict,
    top_tools: list,
    scan_count: int = 1,
) -> bytes:
    buf = BytesIO()

    def on_page(c, doc):
        _header_footer(c, doc, "Executive Summary", org)

    frame = Frame(14*mm, 20*mm, W - 28*mm, H - 52*mm, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=on_page)
    doc = BaseDocTemplate(buf, pagesize=A4, pageTemplates=[template],
                          leftMargin=14*mm, rightMargin=14*mm,
                          topMargin=32*mm, bottomMargin=22*mm)

    s = _styles()
    total = summary.get("total", 0)
    critical = summary.get("critical", 0)
    high = summary.get("high", 0)
    story = []

    # Title block
    story.append(Paragraph("ARGUS / AI SHADOW IT SCANNER", s["crumb"]))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph("Executive Summary", s["h1"]))
    story.append(Paragraph(
        f"Organisation: <b>{org}</b> &nbsp;·&nbsp; "
        f"Scan date: <b>{datetime.utcnow().strftime('%d %B %Y')}</b> &nbsp;·&nbsp; "
        f"Scans run: <b>{scan_count}</b>",
        s["body"]
    ))
    story.append(Spacer(1, 5*mm))

    # KPI strip
    story.append(_kpi_row(summary))
    story.append(Spacer(1, 6*mm))

    # Summary paragraph
    risk_msg = (
        f"<b>{critical} critical-risk</b> and <b>{high} high-risk</b> AI tools were identified "
        f"across {scan_count} scan(s) of your environment. "
        "These tools transmit data outside your organisation's control boundary and may violate "
        "GDPR, data residency, or acceptable use policies."
        if (critical + high) > 0 else
        f"No critical or high-risk tools were identified across {scan_count} scan(s). "
        "Continue monitoring as new AI tools are released frequently."
    )
    story += _section_header("Risk Summary", s)
    story.append(Paragraph(risk_msg, s["body"]))
    story.append(Spacer(1, 4*mm))

    # Top tools table
    story += _section_header("Highest Risk Tools", s)

    if top_tools:
        t_data = [["TOOL", "RISK LEVEL", "SCORE", "DATA LEAVES ORG", "TRAINS ON DATA"]]
        for t in top_tools[:8]:
            p = t.get("raw_profile") or {}
            t_data.append([
                t.get("name", "—"),
                t.get("risk_level", "—"),
                str(t.get("risk_score", "—")),
                "YES" if p.get("data_leaves_org") else "NO",
                "YES" if p.get("trains_on_data")  else "NO",
            ])

        col_w = [(W - 28*mm) * x for x in [0.28, 0.16, 0.10, 0.23, 0.23]]
        tbl = Table(t_data, colWidths=col_w)

        risk_styles = []
        for row_i, row in enumerate(t_data[1:], start=1):
            c_lvl = row[1]
            col = risk_color(c_lvl)
            risk_styles.append(("TEXTCOLOR", (1, row_i), (1, row_i), col))
            risk_styles.append(("TEXTCOLOR", (2, row_i), (2, row_i), col))

        tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,0),  SURFACE),
            ("TEXTCOLOR",    (0,0), (-1,0),  TXT3),
            ("FONTNAME",     (0,0), (-1,0),  "Courier"),
            ("FONTSIZE",     (0,0), (-1,0),  7),
            ("FONTNAME",     (0,1), (-1,-1), "Helvetica"),
            ("FONTSIZE",     (0,1), (-1,-1), 8.5),
            ("TEXTCOLOR",    (0,1), (-1,-1), TXT2),
            ("BACKGROUND",   (0,1), (-1,-1), BG),
            ("ROWBACKGROUNDS",(0,1),(-1,-1), [BG, SURFACE]),
            ("GRID",         (0,0), (-1,-1), 0.4, LINE),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            ("LEFTPADDING",  (0,0), (-1,-1), 7),
        ] + risk_styles))
        story.append(tbl)
    else:
        story.append(Paragraph("No tool data available. Run a scan first.", s["note"]))

    story.append(Spacer(1, 6*mm))

    # Recommendations
    story += _section_header("Recommended Actions", s)
    actions = []
    if critical > 0:
        actions.append(f"<b>Block immediately:</b> {critical} critical-risk tool(s) identified. Enforce DNS/proxy blocks and notify affected users.")
    if high > 0:
        actions.append(f"<b>Review and restrict:</b> {high} high-risk tool(s) detected. Evaluate business need and enforce enterprise licensing with DPAs.")
    if total > 0:
        actions.append("<b>Policy:</b> Publish an approved AI tools list and communicate acceptable use policy to all staff.")
        actions.append("<b>Monitoring:</b> Schedule monthly DNS log ingestion scans and integrate Phase 2 sources (M365, Google Workspace, Okta).")
    if not actions:
        actions.append("No immediate actions required. Continue monthly scanning.")

    for a in actions:
        story.append(Paragraph(f"• &nbsp; {a}", s["body"]))

    doc.build(story)
    return buf.getvalue()


# ── Technical Report ──────────────────────────────────────────────────────────

def build_technical_report(
    org: str,
    summary: dict,
    tools: list,
    scans: list,
) -> bytes:
    buf = BytesIO()

    def on_page(c, doc):
        _header_footer(c, doc, "Technical Report", org)

    frame = Frame(14*mm, 20*mm, W - 28*mm, H - 52*mm, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=on_page)
    doc = BaseDocTemplate(buf, pagesize=A4, pageTemplates=[template],
                          leftMargin=14*mm, rightMargin=14*mm,
                          topMargin=32*mm, bottomMargin=22*mm)

    s = _styles()
    story = []

    # Title
    story.append(Paragraph("ARGUS / AI SHADOW IT SCANNER", s["crumb"]))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph("Technical Report — Full Inventory", s["h1"]))
    story.append(Paragraph(
        f"Organisation: <b>{org}</b> &nbsp;·&nbsp; Generated: <b>{datetime.utcnow().strftime('%d %B %Y %H:%M UTC')}</b>",
        s["body"]
    ))
    story.append(Spacer(1, 5*mm))

    # KPIs
    story.append(_kpi_row(summary))
    story.append(Spacer(1, 6*mm))

    # Scan history
    story += _section_header("Scan History", s)
    if scans:
        sc_data = [["ID", "TYPE", "STATUS", "TOOLS FOUND", "DATE"]]
        for sc in scans:
            sc_data.append([
                f"#{sc.get('id','?')}",
                sc.get("scan_type","—"),
                sc.get("status","—").upper(),
                str(sc.get("tools_found", 0)),
                sc.get("created_at","—")[:10] if sc.get("created_at") else "—",
            ])
        sc_tbl = Table(sc_data, colWidths=[(W-28*mm)*x for x in [0.08,0.18,0.14,0.18,0.42]])
        sc_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0),  SURFACE),
            ("TEXTCOLOR",     (0,0), (-1,0),  TXT3),
            ("FONTNAME",      (0,0), (-1,0),  "Courier"),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("TEXTCOLOR",     (0,1), (-1,-1), TXT2),
            ("FONTNAME",      (0,1), (-1,-1), "Helvetica"),
            ("GRID",          (0,0), (-1,-1), 0.4, LINE),
            ("ROWBACKGROUNDS",(0,1), (-1,-1), [BG, SURFACE]),
            ("TOPPADDING",    (0,0), (-1,-1), 4),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
            ("LEFTPADDING",   (0,0), (-1,-1), 6),
        ]))
        story.append(sc_tbl)
    else:
        story.append(Paragraph("No scans recorded.", s["note"]))

    story.append(Spacer(1, 6*mm))

    # Full tool inventory
    story += _section_header("Full Tool Inventory", s)

    if tools:
        inv_data = [["TOOL", "DOMAIN", "CATEGORY", "RISK", "SCORE", "GDPR", "DATA OUT", "TRAINS"]]
        for t in sorted(tools, key=lambda x: -(x.get("risk_score") or 0)):
            p = t.get("raw_profile") or {}
            inv_data.append([
                t.get("name", "—"),
                t.get("domain", "—") or "—",
                t.get("category", "—") or "—",
                t.get("risk_level", "—"),
                str(t.get("risk_score", "—")),
                t.get("gdpr_relevant", "—") or "—",
                "Y" if p.get("data_leaves_org") else "N",
                "Y" if p.get("trains_on_data")  else "N",
            ])

        cw = [(W-28*mm)*x for x in [0.19,0.16,0.13,0.10,0.08,0.08,0.10,0.10]]  # must sum ≤1
        inv_tbl = Table(inv_data, colWidths=cw, repeatRows=1)

        rl_styles = []
        for ri, row in enumerate(inv_data[1:], start=1):
            col = risk_color(row[3])
            rl_styles += [
                ("TEXTCOLOR", (3, ri), (3, ri), col),
                ("TEXTCOLOR", (4, ri), (4, ri), col),
            ]
            if row[6] == "Y":
                rl_styles.append(("TEXTCOLOR", (6, ri), (6, ri), ORANGE))
            if row[7] == "Y":
                rl_styles.append(("TEXTCOLOR", (7, ri), (7, ri), RED))

        inv_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0),  SURFACE),
            ("TEXTCOLOR",     (0,0), (-1,0),  TXT3),
            ("FONTNAME",      (0,0), (-1,0),  "Courier"),
            ("FONTSIZE",      (0,0), (-1,-1), 7.5),
            ("FONTNAME",      (0,1), (-1,-1), "Helvetica"),
            ("TEXTCOLOR",     (0,1), (-1,-1), TXT2),
            ("GRID",          (0,0), (-1,-1), 0.4, LINE),
            ("ROWBACKGROUNDS",(0,1), (-1,-1), [BG, SURFACE]),
            ("TOPPADDING",    (0,0), (-1,-1), 4),
            ("BOTTOMPADDING", (0,0), (-1,-1), 4),
            ("LEFTPADDING",   (0,0), (-1,-1), 5),
        ] + rl_styles))
        story.append(inv_tbl)
    else:
        story.append(Paragraph("No tools in inventory. Run a DNS CSV scan to populate.", s["note"]))

    story.append(Spacer(1, 6*mm))

    # Per-tool detail cards (top 10 by risk)
    story += _section_header("Tool Detail — Top 10 by Risk Score", s)

    for t in sorted(tools, key=lambda x: -(x.get("risk_score") or 0))[:10]:
        p = t.get("raw_profile") or {}
        level = t.get("risk_level", "UNKNOWN")
        rc = risk_color(level)

        detail_data = [
            [Paragraph(f'<font color="#{rc.hexval()[2:].upper()}" name="Helvetica-Bold" size="10">{t.get("name","—")}</font>', s["body"]),
             Paragraph(f'<font color="#{rc.hexval()[2:].upper()}" name="Courier" size="8">{level} · {t.get("risk_score","—")}/10</font>', s["body"])],
            [Paragraph(f'<font color="{TXT3.hexval()}" size="7">DOMAIN</font><br/>{t.get("domain","—") or "—"}', s["mono"]),
             Paragraph(f'<font color="{TXT3.hexval()}" size="7">VENDOR</font><br/>{t.get("vendor","—") or "—"}', s["mono"])],
            [Paragraph(f'<font color="{TXT3.hexval()}" size="7">DATA LEAVES ORG</font><br/>{"YES" if p.get("data_leaves_org") else "NO"}', s["mono"]),
             Paragraph(f'<font color="{TXT3.hexval()}" size="7">TRAINS ON DATA</font><br/>{"YES" if p.get("trains_on_data") else "NO"}', s["mono"])],
        ]
        if p.get("notes"):
            detail_data.append([
                Paragraph(f'<font color="{TXT3.hexval()}" size="7">NOTES</font><br/>{p["notes"]}', s["mono"]),
                ""
            ])

        half = (W - 28*mm) / 2
        card = Table(detail_data, colWidths=[half, half])
        card.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,-1), SURFACE),
            ("GRID",         (0,0), (-1,-1), 0.4, LINE),
            ("TOPPADDING",   (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            ("LEFTPADDING",  (0,0), (-1,-1), 8),
            ("SPAN",         (0,-1), (-1,-1)) if p.get("notes") else ("NOP",(0,0),(0,0)),
            ("LINEABOVE",    (0,0), (-1,0), 1.5, rc),
        ]))
        story.append(KeepTogether([card, Spacer(1, 3*mm)]))

    doc.build(story)
    return buf.getvalue()
